import DocSidebar from "../ui/Docs/DocSidebar"
import Navbar from "../ui/Docs/Navbar"

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function DocsLayout({ children }) {
    return (
        <main className="bg-neutral-900">
            <Navbar />
            <section className="flex flex-row border border-neutral-700 ">
                <DocSidebar />
                <div className=" p-2">
                    {children}
                </div>
            </section>
        </main>
    )
}
